from sqlalchemy import create_engine, Column, Integer, String, Float, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Database URL (SQLite)
DATABASE_URL = "sqlite:///./jianweidata.db"

# Create Engine
engine = create_engine(
    DATABASE_URL, connect_args={"check_same_thread": False}
)

# SessionLocal
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Base class
Base = declarative_base()

# --- Models ---

class CompanyModel(Base):
    __tablename__ = "companies"
    
    id = Column(String, primary_key=True, index=True)
    Market = Column(Integer, index=True)
    MarketName = Column(String)
    Ticker = Column(String, index=True)
    accFirm = Column(String)
    address = Column(String)
    briefing = Column(Text)
    businessScope = Column(Text)
    chairman = Column(String)
    city = Column(String)
    compProperty = Column(String)
    country = Column(String)
    cpa = Column(String)
    discloser = Column(String)
    email = Column(String)
    employees = Column(Float)
    engName = Column(String)
    fax = Column(String)
    foundDate = Column(String)
    ind1 = Column(String)
    ind2 = Column(String)
    indexMem = Column(String)
    ipoAmount = Column(Float)
    ipoAnnDate = Column(String)
    ipoCollection = Column(Float)
    ipoDilutedPe = Column(Float)
    ipoFee = Column(Float)
    ipoPrice = Column(Float)
    isMargin = Column(String)
    isShort = Column(String)
    isShsc = Column(String)
    isVie = Column(String)
    issueType = Column(String)
    lawFirm = Column(String)
    listBoard = Column(String)
    listDate = Column(String)
    mainBusiness = Column(Text)
    name = Column(String)
    office = Column(String)
    phone = Column(String)
    preNames = Column(String)
    president = Column(String)
    prov = Column(String)
    regCapital = Column(Float)
    registerNumber = Column(String)
    sName = Column(String)
    secretary = Column(String)
    solSig = Column(String)
    sponRep = Column(String)
    sponSor = Column(String)
    stockCode = Column(String, index=True)
    swInd1 = Column(String)
    swInd2 = Column(String)
    swInd3 = Column(String)
    underWriting = Column(String)
    valPe = Column(Float)
    website = Column(String)
    zipcode = Column(String)

class NoticeModel(Base):
    __tablename__ = "notices"
    
    id = Column(String, primary_key=True, index=True)
    Administration = Column(String)
    Availability = Column(String)
    Category = Column(String, index=True)
    DocumentKey = Column(String)
    DocumentNo = Column(String)
    EncryptionKey = Column(String)
    FileType = Column(String) # flexible
    Href = Column(String)
    Industry = Column(String, index=True)
    Institutions = Column(String)
    IntermediaryName = Column(String)
    IntermediaryType = Column(String)
    IsDir = Column(String)
    IsExtracted = Column(String)
    IsFav = Column(String)
    Key = Column(String)
    LawType = Column(String)
    MarketType = Column(String, index=True)
    NoticeType = Column(String, index=True)
    ParentIndustry = Column(String)
    Preview = Column(Text)
    Province = Column(String, index=True)
    PublishDate = Column(String, index=True)
    Publisher = Column(String, index=True)
    Source = Column(Text)
    SourcePath = Column(String)
    StockCode = Column(String, index=True)
    StockTicker = Column(String, index=True)
    Title = Column(String, index=True)
    TotalPage = Column(String)
    Url = Column(String)
    sector = Column(String, index=True)

class EventModel(Base):
    __tablename__ = "events"
    
    id = Column(String, primary_key=True, index=True)
    companies = Column(Text)
    count = Column(Integer)
    en_title = Column(String)
    event_id = Column(String, index=True)
    heat = Column(Float)
    market = Column(String, index=True)
    max_publish_date = Column(String)
    min_publish_date = Column(String)
    sentiment = Column(String) 
    title = Column(String)

class NewsModel(Base):
    __tablename__ = "news"
    
    id = Column(String, primary_key=True, index=True)
    count = Column(Integer)
    enTitle = Column(String)
    event_id = Column(String, index=True)
    newsId = Column(String, index=True)
    source = Column(String)
    time = Column(String, index=True)
    title = Column(String)
    url = Column(String)
    inforId = Column(String, index=True)

class SectorInfoModel(Base):
    __tablename__ = "sector_info"
    
    id = Column(String, primary_key=True, index=True)
    Sector = Column(String, index=True)
    SourceName = Column(String)
    SourceUrl = Column(String)
    # News relationship handled by joining NewsModel via inforId

class IPODataModel(Base):
    __tablename__ = "ipo_data"
    
    id = Column(String, primary_key=True, index=True)
    Issuer = Column(String, index=True)
    LatestDate = Column(String, index=True)
    ListingMarket = Column(String, index=True)
    Status = Column(String, index=True)
    address = Column(String)
    balanceSheet = Column(Text)
    boardSecretary = Column(String)
    businessRegistration = Column(String)
    businessScope = Column(Text)
    cashflowStatement = Column(Text)
    category = Column(String, index=True)
    chairman = Column(String)
    compName = Column(String)
    compType = Column(String)
    companyIntroduction = Column(Text)
    country = Column(String)
    currentTicker = Column(String)
    email = Column(String)
    engName = Column(String)
    establishingTime = Column(String)
    fax = Column(String)
    generalManager = Column(String)
    incomeStatement = Column(Text)
    industry = Column(String)
    ipoCompRFA = Column(String)
    isListed = Column(Integer)
    lawOffice = Column(String)
    legalRepresentative = Column(String)
    listBoard = Column(String)
    netAmountOfRaisedFunds = Column(Float)
    numberEmployees = Column(Integer)
    registeredAddress = Column(String)
    registeredAssets = Column(Float)
    registeredCapital = Column(Float)
    sName = Column(String)
    stockCode = Column(String)
    telePhone = Column(String)
    timeline = Column(Text)
    timingPlan = Column(String)
    topTenShareholders = Column(Text)
    updateTime = Column(String)
    website = Column(String)

class IPORankModel(Base):
    __tablename__ = "ipo_ranks"
    
    id = Column(String, primary_key=True, index=True)
    AcceptDate = Column(String)
    AccountingFirm = Column(String)
    CurrentStatuses = Column(String)
    Entity = Column(String, index=True)
    HasQa = Column(Integer)
    Industry = Column(String)
    LastUpdateDate = Column(String)
    LawFirm = Column(String)
    ListingMarket = Column(String)
    OnsiteInspection = Column(String)
    Rank = Column(Integer)
    Region = Column(String)
    RelatedDocuments = Column(String)
    ReviewQuestions = Column(String)
    Reviewers = Column(String)
    Sector = Column(Integer)
    Sponsor = Column(String)
    address = Column(String)
    balanceSheet = Column(Text)
    boardSecretary = Column(String)
    businessRegistration = Column(String)
    businessScope = Column(Text)
    cashflowStatement = Column(Text)
    category = Column(String, index=True)
    chairman = Column(String)
    compName = Column(String)
    compType = Column(String)
    companyIntroduction = Column(Text)
    country = Column(String)
    currentTicker = Column(String)
    email = Column(String)
    engName = Column(String)
    establishingTime = Column(String)
    fax = Column(String)
    generalManager = Column(String)
    incomeStatement = Column(Text)
    ipoCompRFA = Column(String)
    isListed = Column(Integer)
    lawOffice = Column(String)
    legalRepresentative = Column(String)
    listBoard = Column(String)
    netAmountOfRaisedFunds = Column(Float)
    numberEmployees = Column(Integer)
    registeredAddress = Column(String)
    registeredAssets = Column(Float)
    registeredCapital = Column(Float)
    sName = Column(String)
    stockCode = Column(String)
    telePhone = Column(String)
    timingPlan = Column(String)
    topTenShareholders = Column(Text)
    updateTime = Column(String)
    website = Column(String)

class TimelineDetailModel(Base):
    __tablename__ = "timeline_details"
    
    id = Column(String, primary_key=True, index=True)
    category_id = Column(Integer)
    category_name = Column(String)
    documentId = Column(String)
    documentKey = Column(String)
    fileType = Column(Integer)
    process_result = Column(String)
    publishDate = Column(String)
    sector = Column(Integer)
    stockCode = Column(String, index=True)
    stockTicker = Column(String)
    title = Column(String)
    url = Column(String)
    year = Column(Integer)

class IPOReviewModel(Base):
    __tablename__ = "ipo_reviews"
    
    id = Column(String, primary_key=True, index=True)
    CurrentStatuses = Column(String)
    Entity = Column(String, index=True)
    HasQa = Column(Integer)
    LastUpdateDate = Column(String)
    Rank = Column(Integer)
    RelatedDocuments = Column(Text)
    ReviewQuestions = Column(Text)
    ReviewStatus = Column(String)
    Reviewers = Column(Text)
    Sector = Column(Integer)
    address = Column(String)
    balanceSheet = Column(Text)
    boardSecretary = Column(String)
    businessRegistration = Column(String)
    businessScope = Column(Text)
    cashflowStatement = Column(Text)
    chairman = Column(String)
    compName = Column(String)
    compType = Column(String)
    companyIntroduction = Column(Text)
    country = Column(String)
    currentTicker = Column(String)
    email = Column(String)
    engName = Column(String)
    establishingTime = Column(String)
    fax = Column(String)
    generalManager = Column(String)
    incomeStatement = Column(Text)
    industry = Column(String)
    ipoCompRFA = Column(String)
    isListed = Column(Integer)
    lawOffice = Column(String)
    legalRepresentative = Column(String)
    listBoard = Column(String)
    listingMarket = Column(String)
    netAmountOfRaisedFunds = Column(Float)
    numberEmployees = Column(Integer)
    registeredAddress = Column(String)
    registeredAssets = Column(Float)
    registeredCapital = Column(Float)
    sName = Column(String)
    stockCode = Column(String)
    telePhone = Column(String)
    timingPlan = Column(String)
    topTenShareholders = Column(Text)
    updateTime = Column(String)
    website = Column(String)

class FavoriteNoticeModel(Base):
    __tablename__ = "favorite_notices"
    
    id = Column(String, primary_key=True, index=True)
    notice_id = Column(String, index=True)
    user_id = Column(String, index=True, default="default_user") # Placeholder for user system
    create_time = Column(String)

def init_db():
    Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
